apiVersion: v1
kind: Template
labels:
  template: thefs-api
metadata:
  name: thefs-api
  annotations:
    description: thefs-api
objects:
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: thefs-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: thefs
    template:
      metadata:
        labels:
          app: thefs
      spec:
        containers:
        - name: thefs
          image: samuzzal/thefs:latest
          ports:
          - containerPort: 5000
          livenessProbe:
            httpGet:
              path: /liveness
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /readiness
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
  apiVersion: v1
  kind: Service
  metadata:
    name: thefs-service
  spec:
    selector:
      app: thefs
    ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
    type: LoadBalancer

